import mesh
a= mesh.Mesh()
a.read_bd_file("./DATBDMS.txt")
a.get_edge_info()
a.read_added("./aa.txt",[0,0,-1],-1,"bottom")
a.read_added("./aa.txt",[0,0,1],0,"top")
b= a.extract_mesh(["top"])
c = a.extract_mesh(['body','bottom'])
# b._output_as_fs("./test_fs.txt")
# a._output_as_bd("./test_bd.txt")
